x-common-setup: &common-setup
  volumes:
    - .:/workspace
  working_dir: /workspace
  stdin_open: true
  tty: true
  command: /bin/bash
  environment:
    - PYTHONUNBUFFERED=1
    - HOST_UID=${UID}
    - HOST_GID=${GID}
  user: "${UID}:${GID}"

services:
  dev-cpu:
    <<: *common-setup
    build:
      context: .
      dockerfile: Dockerfile.cpu
    image: llmtimeseries:cpu
    profiles: ["cpu"]

  dev-gpu:
    <<: *common-setup
    build:
      context: .
      dockerfile: Dockerfile.gpu
    image: llmtimeseries:gpu
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    devices:
      - /dev/kfd
      - /dev/dri
    group_add:
      - video
    ipc: host
    shm_size: 8g
    profiles: ["gpu"]
