services:
  dev-cpu:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    image: my-project:cpu
    volumes:
      - .:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true
    command: /bin/bash
    environment:
      - PYTHONUNBUFFERED=1
    profiles: ["cpu"]

  dev-gpu:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    image: my-project:gpu
    volumes:
      - .:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true
    command: /bin/bash
    environment:
      - PYTHONUNBUFFERED=1
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    devices:
      - /dev/kfd
      - /dev/dri
    group_add:
      - video
    ipc: host
    shm_size: 8g
    profiles: ["gpu"]

